/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as QueryUrlIdImport } from './routes/query/$urlId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const QueryUrlIdRoute = QueryUrlIdImport.update({
  id: '/query/$urlId',
  path: '/query/$urlId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/query/$urlId': {
      id: '/query/$urlId'
      path: '/query/$urlId'
      fullPath: '/query/$urlId'
      preLoaderRoute: typeof QueryUrlIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/query/$urlId': typeof QueryUrlIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/query/$urlId': typeof QueryUrlIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/query/$urlId': typeof QueryUrlIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/query/$urlId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/query/$urlId'
  id: '__root__' | '/' | '/query/$urlId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QueryUrlIdRoute: typeof QueryUrlIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QueryUrlIdRoute: QueryUrlIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/query/$urlId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/query/$urlId": {
      "filePath": "query/$urlId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
