/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ResearchNanoIdImport } from './routes/research/$nanoId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResearchNanoIdRoute = ResearchNanoIdImport.update({
  id: '/research/$nanoId',
  path: '/research/$nanoId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/research/$nanoId': {
      id: '/research/$nanoId'
      path: '/research/$nanoId'
      fullPath: '/research/$nanoId'
      preLoaderRoute: typeof ResearchNanoIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/research/$nanoId': typeof ResearchNanoIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/research/$nanoId': typeof ResearchNanoIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/research/$nanoId': typeof ResearchNanoIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/research/$nanoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/research/$nanoId'
  id: '__root__' | '/' | '/research/$nanoId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResearchNanoIdRoute: typeof ResearchNanoIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResearchNanoIdRoute: ResearchNanoIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/research/$nanoId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/research/$nanoId": {
      "filePath": "research/$nanoId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
