name: Run checks

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=8192"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run all checks
        run: bun check:all
